service: serverless-test
app: serverless-test
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  region: us-west-2
functions:
  hellothere:
    handler: handler.hellothere
    events:
      - http:
          path: hellothere
          method: get
          cors: true